### ISSUE TITLE
Sections cause panic, sass isn't processed at all.

### ISSUE THREAD

**Issue by InaccurateTank** [Keats/gutenberg#1932] opened 2022-07-20 04:28 UTC
# Bug Report

## Environment

Zola version: 0.16.0
OS: Windows 10

## Expected Behavior
Sections should be created and sass should be processed.

## Current Behavior
Sections currently cause a panic when being created with any children. Console output with backtrace is:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', components\content\src\library.rs:312:81
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
As for the sass not being processed, I have nothing. It doesn't throw any errors and simply doesn't get added to `./public`.

## Step to reproduce
For Sections:
- Make Folder
- Add `_index.md` with frontmatter
- Add child page

For Sass:
Literally just any file at all in the respective folder. It doesn't do anything.

**Comment by Keats** [comment] 2022-07-20 06:20
>  sass should be processed.

Do you have it turned on in config.toml ? https://github.com/getzola/zola/blob/master/docs/config.toml#L5

As for the panic, it might be a Windows only bug as I can't reproduce it in on macos. Anyone on Windows willing to help debugging it?

**Comment by InaccurateTank** [comment] 2022-07-20 06:38
> Do you have it turned on in config.toml ? https://github.com/getzola/zola/blob/master/docs/config.toml#L5

I do yes, and the reason I'm adding it here is because it works 100% fine if I downgrade to 0.15.3. Did a reinstall to be absolutely sure.

On a second, closer inspection of the output it seems like the paths are mangled? On 0.15.3 the output is this:


```
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 2 pages (0 orphan) and 1 sections

Listening for changes in E:\[path snip]\site-source{config.toml, content, sass, static, templates}
Press Ctrl+C to stop

Web server is available at http://127.0.0.1:1111
Change detected @ 2022-07-19 23:33:25
-> Sass file changed E:\[path snip]\site-source\sass\assets\css\main.scss
Done in 15ms.
```


On 0.16.0 It's this.


```
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 2 pages (2 orphan) and 1 sections
Done in 117ms.

Web server is available at http://127.0.0.1:1111

Listening for changes in \\?\E:\[path snip]\site-source\{config.toml,content,sass,static,templates}
Press Ctrl+C to stop

Change detected @ 2022-07-19 23:34:40
-> Sass file changed \\?\E:\[path snip]\site-source\sass\assets\css\main.scss
Done in 0ms.
```

**Comment by Keats** [comment] 2022-07-20 06:48
Can the site be shared? I don't think we changed anything regarding Sass in 0.16 :/

**Comment by InaccurateTank** [comment] 2022-07-20 07:16
The site source is here: https://github.com/InaccurateTank/site-source
It deploys correctly which probably confirms this is a windows thing?

**Comment by Keats** [comment] 2022-07-20 16:33
Yep, works fine on my macbook. I'll need someone with a Windows machine to figure out what's happening.

**Comment by swiftcoder** [comment] 2022-07-25 16:25
For the SASS issue it looks like we've afoul of https://github.com/rust-lang/glob/issues/111

**Comment by korrat** [comment] 2022-07-30 16:03
Another issue, which seems to be related. When adding an empty `_index.md` directly under content, I get the following error.

```
Building site...
Error: Failed to build the site
Error: Found path collisions:
- `/` from files ["//?/E:/Programmieren/websites/blog/content/_index.md", "\\\\?\\E:\\Programmieren\\websites\\blog\\content\\_index.md"]
```

**Comment by Keats** [comment] 2022-07-30 16:59
It should be fixed in the `next` branch if you want to try

**Comment by korrat** [comment] 2022-07-31 09:25
On my Windows box, I can confirm that `next` fixes the issue with the top-level `_index.md`, and rust-lang/glob#112 fixes Sass files not being compiled. It seems that `next` also fixes the issue when generating sections, but I'm unable to reproduce the issue on the master branch.

**Closed as completed** 2022-08-14 19:34 UTC
Labels: bug, Need Windows help
