### ISSUE TITLE
Are there duplicates of packages?

### ISSUE THREAD

**Issue by joyously** [Keats/gutenberg#1804] opened 2022-03-18 18:29 UTC
# Bug Report
I downloaded the latest zip of source code and ran `cargo build`. It compiles fine, but there are some packages that are listed twice, with different versions. Does that make the executable larger? Does it mean some parts don't have fixes that other parts have?
I sorted the list and here are the duplicates I see
```
   Compiling arrayvec v0.5.2
   Compiling arrayvec v0.4.12
   Compiling block-buffer v0.7.3
   Compiling block-buffer v0.9.0
   Compiling bytecount v0.3.2
   Compiling bytecount v0.6.2
   Compiling bytes v0.4.12
   Compiling bytes v1.1.0
   Compiling cfg-if v1.0.0
   Compiling cfg-if v0.1.10
   Compiling digest v0.9.0
   Compiling digest v0.8.1
   Compiling generic-array v0.12.4
   Compiling generic-array v0.14.5
   Compiling getrandom v0.2.4
   Compiling getrandom v0.1.16
   Compiling itoa v0.4.8
   Compiling itoa v1.0.1
   Compiling miniz_oxide v0.3.7
   Compiling miniz_oxide v0.4.4
   Compiling mio v0.6.23
   Compiling mio v0.7.14
   Compiling nom_locate v1.0.0
   Compiling nom_locate v2.1.0
   Compiling opaque-debug v0.3.0
   Compiling opaque-debug v0.2.3
   Compiling phf v0.8.0
   Compiling phf v0.10.1
   Compiling phf_codegen v0.8.0
   Compiling phf_codegen v0.10.0
   Compiling phf_generator v0.8.0
   Compiling phf_generator v0.10.0
   Compiling phf_shared v0.10.0
   Compiling phf_shared v0.8.0
   Compiling rand v0.7.3
   Compiling rand v0.8.4
   Compiling rand_chacha v0.2.2
   Compiling rand_chacha v0.3.1
   Compiling rand_core v0.5.1
   Compiling rand_core v0.6.3
   Compiling time v0.1.43
   Compiling time v0.3.6
```

## Environment
Ubuntu Studio 20.04 LTS

Zola version: 0.15.3

**Comment by Keats** [comment] 2022-03-18 21:57
Yep there are duplicates due to various dependencies dependencies. Some of it can be fixed via updating PRs (eg https://github.com/mattico/elasticlunr-rs/pull/42) but some libraries like https://github.com/bcmyers/num-format might not be maintained anymore and that's trickier short of forking all of them.

It's not a bug and won't cause issues in practice and the executable will be a tiny bit larger but not much can be done other than PRs to other projects.

I'll close the issue as it's really an ongoing process. If you have `cargo tree` installed, you can easily find the dupes by running `cargo tree -d`

**Closed as completed by Keats** 2022-03-18 21:57 UTC
