### ISSUE TITLE
`{{ config.title }}` in theme template file not populating 

### ISSUE THREAD

**Issue by jklamer** [Keats/gutenberg#2072] opened 2023-01-15 20:01 UTC
# Bug Report
Theme template using `{{ config.title }}` is not populating when title is in base level of config.toml. When the theme's template is changed to `{{ config.extra.title }}` the value is populated.
## Environment
MacOs
Zola version:
`zola 0.16.1`
## Expected Behavior
The title in the config generated in the HTML.

## Current Behavior
Empty content instead

## Step to reproduce
Configure project with a theme that uses `{{ config.title }}` (ex https://github.com/longfangsong/anatole-zola). Populate title in base level of config. Zola serve/zola build. Observe no content in the generated HTML

**Comment by Keats** [comment] 2023-01-15 21:42
I think this will be fixed by https://github.com/getzola/zola/pull/2039. I'll merge it soon and try to reproduce.

**Comment by Keats** [comment] 2023-01-17 20:18
Yep that works for me with `next` branch, can you try?

**Closed as completed** 2023-02-17 13:07 UTC
Labels: done in pr
