### ISSUE TITLE
Zola Built From Source With The Following Warnings

### ISSUE THREAD

**Issue by ajbozdar** [Keats/gutenberg#2635] opened 2024-09-11 14:11 UTC
# Bug Report

## Environment
Zola version: 0.19.2

## Expected Behavior
The compilation process should have started and ended without warnings. The warnings include possible deprecation of packages.

## Current Behavior
Zola took 23m 16s to build from source. It included five warnings which are given below:  

**Before downloading packages:**
warning: package `bytemuck v1.16.0` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked  
warning: package `bytes v1.6.0` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked  
warning: package `zerovec v0.10.2` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked  
warning: package `zerovec-derive v0.10.2` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked  

**After compiling**
warning: the following packages contain code that will be rejected by a future version of Rust: quick-xml v0.17.2

## Step to reproduce
Simply build Zola from source on an up to date Fedora 40 instance

### Notes
A similar issue was also opened for zola v0.17.2 last year. It is still pending. [getzola#2290](https://github.com/getzola/zola/issues/2290)

**Comment by Keats** [comment] 2024-09-11 14:19
None of those issues are bad (except eventually the quick-xml one). The yanked will be fixed automatically for the next version and the quick-xml crate needs to be replaced with another crate as it's not really maintained.

Closing as this is essentially a duplicate of https://github.com/getzola/zola/issues/2452

**Closed as completed by Keats** 2024-09-11 14:19 UTC
