### ISSUE TITLE
CSS syntax highlighting + line numbers generates in invalid HTML

### ISSUE THREAD

**Issue by jhpratt** [Keats/gutenberg#1994] opened 2022-09-22 01:51 UTC
# Bug Report

## Environment

Zola version: 0.16.1

## Step to reproduce

```sh
zola init
echo 'base_url = "https://example.com"\nminify_html = true\n[markdown]\nhighlight_code = true\nhighlight_theme = "css"' > config.toml
echo '+++\n+++\n\n```rust,linenos\nfn\n```\n\nfoo\n' > content/_index.md
echo '{{ section.content | safe }}' > templates/index.html
zola serve --open
```

Just press enter repeatedly for the prompts. It'll be overridden by this script.

## Expected Behavior

HTML code is minified properly.

## Current Behavior

Manually formatting the minified code results in this:

```html
<pre class="language-rust z-code" data-lang=rust data-linenos>
    <code class=language-rust data-lang=rust>
        <table>
            <tbody>
                <tr>
                    <td>1<td>
                        <span class="z-source z-rust">
                            <span class="z-storage z-type z-function z-rust">fn</span>
<td><tr><span><tbody><table><code><pre>
<p>foo</p>
```

Note that the second to last line _opens_, rather than _closes_, the tags. 

Now comment out `minify_html = true` in `config.toml` and run `zola serve`. The HTML generated follows (manually formatted again):

```html
<pre data-linenos data-lang="rust" class="language-rust z-code">
    <code class="language-rust" data-lang="rust">
        <table>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>
                        <span class="z-source z-rust">
                            <span class="z-storage z-type z-function z-rust">fn</span>
                    </td>
                </tr>
                        </span>
            </tbody>
        </table>
    </code>
</pre>
<p>foo</p>
```

Better, as the tags are at least closed here. However, they are still not in the correct order. I have shown this with indentation. `</span>` must be _before_ `</td>`.

My suspicion is that the minifier is incapable of handling the invalid HTML — tags **must** be closed in the reverse order they are opened in. Browsers appear capable of handling the unminified code, although the minified code completely breaks the rest of the page.

**Comment by Keats** [comment] 2022-09-22 07:00
Duplicate of https://github.com/getzola/zola/issues/1994
We should fix the random span showing up

**Closed as completed by Keats** 2022-09-22 07:00 UTC

**Comment by jhpratt** [comment] 2022-09-22 07:27
This is #1994 :slightly_smiling_face: 

To be clear it's not a random span, it's just closed in the wrong spot. That's what I tried to show with the indentation in the second example.

I'll probably take a look into this myself tomorrow anyways.

**Comment by Keats** [comment] 2022-09-22 07:31
Argh I meant https://github.com/getzola/zola/issues/1942

Yep for the span I meant we need to fix it
