### ISSUE TITLE
Supported language Java is not highlighted properly

### ISSUE THREAD

**Issue by Ihsahn** [Keats/gutenberg#1653] opened 2021-11-08 20:16 UTC
# Bug Report

## Environment
linux, zola from snap

Zola version:
`zola 0.14.1`

## Expected Behavior
![obraz](https://user-images.githubusercontent.com/8476571/140811449-8e262b54-3fd7-4164-a897-692d9500af75.png)
## Current Behavior
![obraz](https://user-images.githubusercontent.com/8476571/140811430-3ec3bd2c-62a1-4be4-af52-44d215222a67.png)

## Step to reproduce
1. in config.toml:

`highlight_code = true`

2. In a page .md source, add a java code block:
```
/**
 * @author Some Author
 */
public class MyClass {

 private final HashMap<String, String> myHashMap = new HashMap<>();

 public MyClass() {
  init();
 }
}
```

**Comment by Ihsahn** [comment] 2021-11-08 20:17
Workaround: use syntax from https://github.com/sublimehq/Packages/blob/master/Java/Java.sublime-syntax

**Comment by Keats** [comment] 2021-11-09 12:30
The issue is that we cannot update the official syntaxes as a lot of them are using an updated syntax that `syntect`, the syntax highlighting library doesn't support. We could keep a repo where we can update them individually instead of the whole git repo but that's a big chunk of work.
Happy to point directions if someone wants to contribute that, it would also solve https://github.com/trishume/syntect/issues/333

Another alternative is having a port of `pygments`, I have a project that's like 20% there but can't find the time to work on it.

**Comment by Keats** [comment] 2023-01-17 23:29
There are a few other issues on that topic, closing this one to avoid keeping too many open

**Closed as completed by Keats** 2023-01-17 23:29 UTC
