### ISSUE TITLE
Zola v0.14.1+ doesn't work on CloudFlare pages anymore

### ISSUE THREAD

**Issue by rtsisyk** [Keats/gutenberg#1982] opened 2022-09-08 06:39 UTC
# Bug Report

## Environment

Zola version: v0.14.0, v0.15.1, v0.16.1

## Expected Behavior

```
09:39:17.394 | Installing Zola 0.14.0
-- | --
09:39:18.228 | Started restoring cached go cache
09:39:18.248 | Finished restoring cached go cache
09:39:18.391 | go version go1.14.4 linux/amd64
09:39:18.406 | go version go1.14.4 linux/amd64
09:39:18.409 | Installing missing commands
09:39:18.410 | Verify run directory
09:39:18.410 | Executing user command: zola build
09:39:18.425 | Building site...
```

## Current Behavior

```
09:35:19.992 | Installing Zola 0.15.3
-- | --
09:35:20.873 | Started restoring cached go cache
09:35:20.892 | Finished restoring cached go cache
09:35:21.039 | go version go1.14.4 linux/amd64
09:35:21.053 | go version go1.14.4 linux/amd64
09:35:21.056 | Installing missing commands
09:35:21.057 | Verify run directory
09:35:21.057 | Executing user command: zola build
09:35:21.068 | zola: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by zola)
09:35:21.069 | zola: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by zola)
09:35:21.069 | zola: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by zola)
09:35:21.074 | Failed: build command exited with code: 1
09:35:21.851 | Failed: an internal error occurred
```

```
09:33:10.927 | Installing Zola 0.16.1
-- | --
09:33:11.803 | Started restoring cached go cache
09:33:11.824 | Finished restoring cached go cache
09:33:11.976 | go version go1.14.4 linux/amd64
09:33:11.992 | go version go1.14.4 linux/amd64
09:33:11.995 | Installing missing commands
09:33:11.995 | Verify run directory
09:33:11.996 | Executing user command: zola build
09:33:12.005 | zola: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by zola)
09:33:12.005 | zola: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by zola)
09:33:12.006 | zola: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by zola)
09:33:12.006 | zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by zola)
09:33:12.006 | zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by zola)
09:33:12.006 | zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by zola)
09:33:12.006 | zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by zola)
09:33:12.011 | Failed: build command exited with code: 1
09:33:12.766 | Failed: an internal error occurred
```

Please use the previous version of Linux distro to build the release binaries.

**Comment by bellanotteunicorn** [comment] 2022-09-08 11:09
i also have the same problem with zola and cloudflare , for now you have to build it locally "zola build" and after that you pull to github repo and cloudflare will automatically build your web , and for cloudflare for build settings just input "public " in the output directory

**Comment by bellanotteunicorn** [comment] 2022-09-08 11:09
> # Bug Report
> ## Environment
> Zola version: v0.14.0, v0.15.1, v0.16.1
> 
> ## Expected Behavior
> ```
> 09:39:17.394 | Installing Zola 0.14.0
> -- | --
> 09:39:18.228 | Started restoring cached go cache
> 09:39:18.248 | Finished restoring cached go cache
> 09:39:18.391 | go version go1.14.4 linux/amd64
> 09:39:18.406 | go version go1.14.4 linux/amd64
> 09:39:18.409 | Installing missing commands
> 09:39:18.410 | Verify run directory
> 09:39:18.410 | Executing user command: zola build
> 09:39:18.425 | Building site...
> ```
> 
> ## Current Behavior
> ```
> 09:35:19.992 | Installing Zola 0.15.3
> -- | --
> 09:35:20.873 | Started restoring cached go cache
> 09:35:20.892 | Finished restoring cached go cache
> 09:35:21.039 | go version go1.14.4 linux/amd64
> 09:35:21.053 | go version go1.14.4 linux/amd64
> 09:35:21.056 | Installing missing commands
> 09:35:21.057 | Verify run directory
> 09:35:21.057 | Executing user command: zola build
> 09:35:21.068 | zola: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by zola)
> 09:35:21.069 | zola: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by zola)
> 09:35:21.069 | zola: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by zola)
> 09:35:21.074 | Failed: build command exited with code: 1
> 09:35:21.851 | Failed: an internal error occurred
> ```
> 
> ```
> 09:33:10.927 | Installing Zola 0.16.1
> -- | --
> 09:33:11.803 | Started restoring cached go cache
> 09:33:11.824 | Finished restoring cached go cache
> 09:33:11.976 | go version go1.14.4 linux/amd64
> 09:33:11.992 | go version go1.14.4 linux/amd64
> 09:33:11.995 | Installing missing commands
> 09:33:11.995 | Verify run directory
> 09:33:11.996 | Executing user command: zola build
> 09:33:12.005 | zola: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by zola)
> 09:33:12.005 | zola: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by zola)
> 09:33:12.006 | zola: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by zola)
> 09:33:12.006 | zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by zola)
> 09:33:12.006 | zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by zola)
> 09:33:12.006 | zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by zola)
> 09:33:12.006 | zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by zola)
> 09:33:12.011 | Failed: build command exited with code: 1
> 09:33:12.766 | Failed: an internal error occurred
> ```
> 
> Please use the previous version of Linux distro to build the release binaries.

i also have the same problem with zola and cloudflare , for now you have to build it locally "zola build" and after that you pull to github repo and cloudflare will automatically build your web , and for cloudflare for build settings just input "public " in the output directory

**Comment by Keats** [comment] 2022-09-08 11:16
That's likely their image that uses a Linux version too old? What is it?

**Comment by biodranik** [comment] 2022-09-11 23:03
I reported that issue on Cloudflare's Discord channel about half a year ago. They're using some old image, and for some reason, it was not their priority to upgrade it.

**Comment by Keats** [comment] 2023-01-12 22:22
Closing as duplicate of https://github.com/getzola/zola/issues/1713

**Closed as completed by Keats** 2023-01-12 22:22 UTC
