### ISSUE TITLE
Markdown: Add terraform syntax highlighting support

### ISSUE THREAD

**Issue by jpcaruana** [Keats/gutenberg#2067] opened 2023-01-03 16:06 UTC
It would be great to be able to format `.tf` code (https://www.terraform.io/)

**Comment by Aju100** [comment] 2023-01-10 17:58
Hey Can I work on this issue @jpcaruana

**Comment by SkypLabs** [comment] 2023-01-17 00:33
Duplicate of #1981.

**Comment by Keats** [comment] 2023-01-17 09:46
Good catch, closing this one.

**Closed as completed by Keats** 2023-01-17 09:46 UTC

**Comment by jpcaruana** [comment] 2023-01-17 09:52
oups sorry for the duplicate
